language: ruby
cache: bundler
bundler_args: "--without production --retry 3"
rvm:
# - 1.9.3
- 2.0
- 2.2
- ruby-head
# - jruby-19mode
# - jruby-head
env:
- DB=sqlite
- DB=mysql
- DB=postgresql
before_install:
- cp config/database.yml.$DB config/database.yml
- gem update bundler
before_script:
- bundle exec rake db:drop RAILS_ENV=test
- bundle exec rake db:create RAILS_ENV=test
- bundle exec rake db:migrate RAILS_ENV=test
branches:
  only:
  - master
notifications:
  email:
  - iqvoc@innoq.com
addons:
  postgresql: "9.3"
